/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tanukisoftware_wrapper_WrapperResources */

#ifndef _Included_org_tanukisoftware_wrapper_WrapperResources
#define _Included_org_tanukisoftware_wrapper_WrapperResources
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: m_outError */
/* Inaccessible static: m_validateResourceKeys */
/* Inaccessible static: EMPTY_OBJECT_ARRAY */
/* Inaccessible static: class_00024org_00024tanukisoftware_00024wrapper_00024WrapperResources */
/*
 * Class:     org_tanukisoftware_wrapper_WrapperResources
 * Method:    nativeGetLocalizedString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tanukisoftware_wrapper_WrapperResources_nativeGetLocalizedString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tanukisoftware_wrapper_WrapperResources
 * Method:    nativeDestroyResource
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tanukisoftware_wrapper_WrapperResources_nativeDestroyResource
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
